# Generated by Django 5.0.7 on 2024-08-06 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='task name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('task_type', models.CharField(choices=[('SD', 'Service Desk'), ('ESK', 'Eskalacje'), ('MFIF', 'MFIF'), ('SNOW', 'ServiceNow'), ('EIR', 'EIR'), ('MON', 'Monitoring'), ('OTHER', 'Other')], max_length=5, verbose_name='task type')),
                ('duration', models.DurationField(help_text='Expected duration of the task', verbose_name='duration')),
                ('is_cyclical', models.BooleanField(default=False, verbose_name='is cyclical')),
                ('cycle_time', models.DurationField(blank=True, help_text='Time between cycles for cyclical tasks', null=True, verbose_name='cycle time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
    ]
