# Generated by Django 5.0.7 on 2024-08-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user availability',
                'verbose_name_plural': 'user availabilities',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
