# Generated by Django 5.0.7 on 2024-08-06 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'daily plan',
                'verbose_name_plural': 'daily plans',
            },
        ),
        migrations.CreateModel(
            name='DailyPlanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.dailyplan')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'daily plan task',
                'verbose_name_plural': 'daily plan tasks',
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='tasks',
            field=models.ManyToManyField(through='plans.DailyPlanTask', to='tasks.task'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('date', 'user')},
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(verbose_name='month')),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monthly plan',
                'verbose_name_plural': 'monthly plans',
                'unique_together': {('month', 'year', 'user')},
            },
        ),
    ]
